---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: call_Ansible_Post_config_VM
    inherits: 
    description: 
  fields:
  - catalogItem:
      value: CC-ansible-bootstrap
  - extravar1:
      value: "'test'"
  - execute:
      value: call_Ansible_Item
