---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Ansible_Post_config_VM
    inherits: 
    description: 
  fields:
  - Ansible1:
      value: "/Service/Provisioning/StateMachines/StateMachines_Ansible/Ansible_Bootstrap"
  - Ansible2:
      value: "/Service/Provisioning/StateMachines/Wrapper_Ansible/call_Ansible_Post_config_VM"
  - Ansible3:
      value: "/Service/Provisioning/StateMachines/Wrapper_Ansible/checkAnsibleProvisionned"
